from fpdf import FPDF
from datetime import datetime

# --- Configuration ---
BANK_NAME = "Your Corporate Bank"
APP_NAME = "OpportunityNavigator AI" # Or your chosen app name
OUTPUT_FILENAME = "Loan_Application_GreenLeaf_Organics_ASCII.pdf" # Changed filename
CLIENT_NAME = "GreenLeaf Organics Ltd."
CONTACT_PERSON = "Jane Doe"
CONTACT_POSITION = "CEO"

# --- Font Configuration (Using built-in font) ---
FONT_FAMILY_NAME = "Arial" # Or "Helvetica", "Times", "Courier"

# --- Helper Functions (Using built-in font) ---
def add_section_title(pdf, title):
    pdf.set_font(FONT_FAMILY_NAME, "B", 14)
    pdf.cell(0, 10, title, 0, 1, "L")
    pdf.ln(2)

def add_table_header(pdf, headers, col_widths):
    pdf.set_font(FONT_FAMILY_NAME, "B", 9)
    pdf.set_fill_color(220, 220, 220)
    for i, header in enumerate(headers):
        pdf.cell(col_widths[i], 7, header, 1, 0, "C", fill=True)
    pdf.ln()

def add_table_row(pdf, data, col_widths, highlight_attention=False):
    default_font_size = 9

    for i, item_text in enumerate(data):
        current_style = ""
        if highlight_attention:
            if "[ATTENTION REQUIRED]" in item_text:
                current_style = "B"
            elif "[TO BE CONFIRMED BY CLIENT]" in item_text:
                current_style = "BI"

        pdf.set_font(FONT_FAMILY_NAME, current_style, default_font_size)
        pdf.multi_cell(col_widths[i], 7, str(item_text), border=1, align="L", new_x="RIGHT", new_y="TOP", max_line_height=pdf.font_size)

    pdf.ln(7)


def add_key_value_pair(pdf, key, value, source_note=""):
    pdf.set_font(FONT_FAMILY_NAME, "B", 9)
    pdf.cell(60, 7, key, 0, 0, "L")
    pdf.set_font(FONT_FAMILY_NAME, "", 9)
    pdf.multi_cell(0, 7, value, 0, 1, "L")
    if source_note:
        pdf.set_font(FONT_FAMILY_NAME, "I", 7)
        pdf.set_text_color(128, 128, 128)
        pdf.cell(60, 4, "", 0, 0)
        pdf.multi_cell(0, 4, f"Source: {source_note}", 0, 1, "L")
        pdf.set_text_color(0, 0, 0)
    pdf.ln(1)


class PDF(FPDF):
    def header(self):
        # self.image('your_bank_logo.png', 10, 8, 33)
        self.set_font(FONT_FAMILY_NAME, "B", 15)
        self.cell(0, 10, BANK_NAME, 0, 1, "C")
        self.set_font(FONT_FAMILY_NAME, "B", 12)
        self.cell(0, 8, "BUSINESS LOAN APPLICATION FORM (DRAFT)", 0, 1, "C")
        self.set_font(FONT_FAMILY_NAME, "I", 9)
        self.cell(0, 6, f"Auto-Generated by {APP_NAME}", 0, 1, "C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font(FONT_FAMILY_NAME, "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | {CLIENT_NAME} - Draft Loan Application | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 0, "C")

# --- Create PDF Document ---
pdf = PDF()
# NO pdf.add_font() calls needed for built-in fonts

pdf.alias_nb_pages()
pdf.add_page()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.set_left_margin(15)
pdf.set_right_margin(15)

# Set default font for the document
pdf.set_font(FONT_FAMILY_NAME, "", 10)

# --- Application Header Info ---
pdf.cell(0, 7, f"Application Date (Auto-Generated): {datetime.now().strftime('%Y-%m-%d')}", 0, 1)
pdf.cell(0, 7, f"Prepared For: {CLIENT_NAME}", 0, 1)
pdf.ln(5)

pdf.set_font(FONT_FAMILY_NAME, "I", 9)
pdf.multi_cell(0, 5, "Instructions: This application form has been partially pre-filled using information gathered by the OpportunityNavigator AI system from internal and external data sources. Please review all information carefully. Fields marked with emphasis need specific input or confirmation from the client. This document is a draft and requires client verification and signature before formal submission.", 0, "L")
pdf.ln(5)

# --- SECTION 1: APPLICANT DETAILS ---
add_section_title(pdf, "SECTION 1: APPLICANT DETAILS")
sec1_headers = ["Field", "Value", "Source Indication (Internal Note)"]
sec1_col_widths = [60, 80, 40]
add_table_header(pdf, sec1_headers, sec1_col_widths)
sec1_data = [
    ["Registered Company Name:", CLIENT_NAME, "Companies House #09876543"],
    ["Company Registration No.:", "09876543", "Companies House"],
    ["Date of Incorporation:", "Approx. 8 years ago", "Companies House/Internal"],
    ["Trading Address:", "Unit 5, Willowbrook Industrial Estate, Reading, RG2 0TD", "Internal CRM"],
    ["Primary Contact Person:", CONTACT_PERSON, "Internal CRM"],
    ["Position:", CONTACT_POSITION, "Internal CRM"],
    ["Contact Email:", "j.doe@greenleaforganics.co.uk", "Internal CRM"],
    ["Contact Phone:", "0118 9XXXXXX", "Internal CRM (SalesForce)"],
    ["Years in Business:", "Approx. 8 years (Client with bank for 7 years)", "Internal Client Module"],
    ["Industry / Sector:", "Organic Food & Beverage Production", "External Research/Website"],
    ["Number of Employees:", "Est. 20-50 (To be confirmed)", "External Research (e.g., LinkedIn)"],
    ["Website:", "www.greenleaforganics.co.uk (Assumed)", "External Research"]
]
for row in sec1_data:
    add_table_row(pdf, row, sec1_col_widths)
pdf.ln(5)

# --- SECTION 2: LOAN REQUIREMENTS ---
add_section_title(pdf, "SECTION 2: LOAN REQUIREMENTS")
sec2_headers = ["Field", "Value", "Source Indication (Internal Note)"]
sec2_col_widths = [60, 80, 40]
add_table_header(pdf, sec2_headers, sec2_col_widths)
sec2_data = [
    ["Loan Amount Requested:", "[ATTENTION REQUIRED - RD TO DISCUSS WITH CLIENT]", "Client Input Needed"],
    ["Purpose of Loan:", "Investment in a new bottling and packaging line to meet escalating demand and to expand distribution network nationwide.", "External (Annual Report Analysis) / CRM"],
    ["Proposed Loan Term:", "[ATTENTION REQUIRED - RD TO DISCUSS WITH CLIENT]", "Client Input Needed"],
    ["Proposed Repayment Source:", "Increased revenue and profits from expanded production capacity and market reach.", "Analysis Agent Synthesis"],
    ["Specific Assets to be Financed:", "New bottling and packaging line", "Inferred from Purpose"]
]
for row in sec2_data:
    add_table_row(pdf, row, sec2_col_widths, highlight_attention=True)
pdf.ln(5)

# --- SECTION 3: BUSINESS FINANCIAL INFORMATION (FYE 2023) ---
add_section_title(pdf, "SECTION 3: BUSINESS FINANCIAL INFORMATION (Most Recent Full Year - FYE 2023)")
sec3_headers = ["Field", "Value", "Source Indication (Internal Note)"]
sec3_col_widths = [70, 70, 40]
add_table_header(pdf, sec3_headers, sec3_col_widths)
sec3_data = [
    ["Annual Turnover (FYE 2023):", "GBP 3,500,000", "Companies House"], # Changed currency symbol
    ["Gross Profit (FYE 2023):", "See Filed Accounts", "Companies House"],
    ["Net Profit (FYE 2023):", "GBP 450,000", "Companies House"], # Changed currency symbol
    ["Net Assets (FYE 2023):", "GBP 1,200,000 (Example)", "Companies House"], # Changed currency symbol
    ["Avg Bank Balance (Last 12m - Primary Current A/C with us):", "GBP 150,000", "Internal Core Banking"], # Changed currency symbol
    ["Existing Bank Loans/Facilities (with us):", "Equipment Loan (Facility ID: EL4567)", "Internal Lending System"],
    ["  Original Amount:", "GBP 50,000", "Internal Lending System"], # Changed currency symbol
    ["  Current Balance (approx.):", "GBP 10,400", "Internal Lending System"], # Changed currency symbol
    ["  Remaining Term:", "12 months", "Internal Lending System"],
    ["  Repayment Record:", "Perfect", "Internal Lending System"],
    ["Other Significant External Borrowings:", "Debenture with FinSecure Lenders PLC, maturing November 2025.", "Companies House (Charges Register)"],
    ["  Amount Outstanding:", "[TO BE CONFIRMED BY CLIENT]", "Client Input Needed"]
]
for row in sec3_data:
    add_table_row(pdf, row, sec3_col_widths, highlight_attention=True)
pdf.ln(5)

# --- SECTION 4: MANAGEMENT & OWNERSHIP ---
add_section_title(pdf, "SECTION 4: MANAGEMENT & OWNERSHIP")
sec4_headers = ["Field", "Value", "Source Indication (Internal Note)"]
sec4_col_widths = [60, 80, 40]
add_table_header(pdf, sec4_headers, sec4_col_widths)
sec4_data = [
    ["Key Directors / Owners:", f"{CONTACT_PERSON} ({CONTACT_POSITION})", "CRM / Companies House"],
    ["", "John Smith (Director - Example)", "Companies House"],
    ["Brief Management Experience:", f"{CONTACT_PERSON}: Experienced leader in food sector (To be expanded)", "External Research / CRM"],
    ["Shareholding Structure (Major):", "Primarily held by Jane Doe (To be confirmed)", "Companies House / Client Input"]
]
for row in sec4_data:
    add_table_row(pdf, row, sec4_col_widths, highlight_attention=True)
pdf.ln(5)


# --- SECTION 5: SUPPORTING INFORMATION & MARKET OUTLOOK (SUMMARY) ---
add_section_title(pdf, "SECTION 5: SUPPORTING INFORMATION & MARKET OUTLOOK (SUMMARY)")
pdf.set_font(FONT_FAMILY_NAME, "", 9)
# Using asterisk for bullet points
pdf.multi_cell(0, 5, "* Recent Business Performance Summary: Turnover up 40% YoY, Net Profit up 25% YoY (FYE 2023). Average bank balances with us increased 35% in the last 12 months.\n  (Source: Aggregation from Companies House & Internal Banking System)", 0, "L")
pdf.ln(2)
pdf.multi_cell(0, 5, "* Market Outlook Summary: Organic Food & Beverage Market UK projected 8-10% CAGR (next 3 years). GreenLeaf Organics highlighted as a \"rising star\" in industry publications.\n  (Source: MarketScan Ltd Report Q1 2024 & Food Business News Article Scan)", 0, "L")
pdf.ln(2)
pdf.multi_cell(0, 5, "* Proposed Security (Initial Indication): To be discussed. Potential for charge over new assets financed and review of existing security structure.\n  (Source: Bank Policy Agent - Standard Security Requirements)", 0, "L")
pdf.ln(5)

# --- SECTION 6: SUPPORTING DOCUMENTS CHECKLIST ---
add_section_title(pdf, "SECTION 6: SUPPORTING DOCUMENTS CHECKLIST")
pdf.set_font(FONT_FAMILY_NAME, "I", 9)
pdf.multi_cell(0,5,"Please attach the following documents. Items marked [X] have been identified/sourced by OpportunityNavigator AI.",0,"L") # Updated instruction
pdf.ln(2)

sec6_headers = ["Document", "Client to Attach/Confirm", "AI Found/Identified"]
sec6_col_widths = [100, 40, 40]
add_table_header(pdf, sec6_headers, sec6_col_widths)
# Using [ ] and [X] for checkboxes
sec6_data = [
    ["Last 3 Years Audited/Filed Financial Accounts", "[ ]", "[X]"],
    ["Management Accounts (Year-to-Date)", "[ ]", "[ ]"],
    ["Business Plan for Expansion Project", "[ ]", "[ ]"],
    ["Financial Projections (3-5 years)", "[ ]", "[ ]"],
    ["Aged Debtors & Creditors List", "[ ]", "[ ]"],
    ["Bank Statements (Last 6 months, non-our bank)", "[ ]", "[ ]"],
    [f"Director(s) CVs / Profiles ({CONTACT_PERSON})", "[ ]", "[X] (Partial)"],
    ["Proof of ID & Address for Directors", "[ ]", "[ ]"]
]
for row in sec6_data:
    add_table_row(pdf, row, sec6_col_widths)
pdf.ln(5)

# --- SECTION 7: DECLARATIONS ---
add_section_title(pdf, "SECTION 7: DECLARATIONS")
pdf.set_font(FONT_FAMILY_NAME, "", 9)
pdf.multi_cell(0, 5, f"I/We declare that the information provided in this application and any attached documents is true, complete, and accurate to the best of my/our knowledge. I/We authorize {BANK_NAME} to make any necessary inquiries to verify this information, including credit checks on the company and its directors/guarantors. I/We understand that providing false or misleading information may lead to the rejection of this application or termination of any facility granted.\n\nI/We acknowledge that this auto-generated draft requires our full review and confirmation of all details, particularly those marked for attention.", 0, "L")
pdf.ln(5)

# --- SECTION 8: SIGNATURES ---
add_section_title(pdf, "SECTION 8: SIGNATURES")
pdf.set_font(FONT_FAMILY_NAME, "", 10)
pdf.cell(0, 7, f"For and on behalf of {CLIENT_NAME}:", 0, 1)
pdf.ln(15)
pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 70, pdf.get_y())
pdf.ln(5)
pdf.cell(70, 7, "Signature", 0, 0)
pdf.cell(0, 7, f"Name: {CONTACT_PERSON}", 0, 1)
pdf.cell(70, 7, "", 0, 0)
pdf.cell(0, 7, f"Position: {CONTACT_POSITION}", 0, 1)
pdf.cell(70, 7, "", 0, 0)
pdf.cell(0, 7, "Date: ___________________", 0, 1)
pdf.ln(10)

pdf.set_font(FONT_FAMILY_NAME, "B", 10)
pdf.cell(0,10, "For Bank Use Only:",0,1)
pdf.set_font(FONT_FAMILY_NAME, "", 10)
pdf.cell(0,7, "Application Received By: ___________________ Date: _______________",0,1)
pdf.cell(0,7, "Initial Assessment Notes:",0,1)
pdf.rect(pdf.get_x(), pdf.get_y(), pdf.get_string_width("Application Received By: ___________________ Date: _______________") if pdf.get_string_width("Application Received By: ___________________ Date: _______________") > 170 else 180 , 30)
pdf.ln(35)


# --- Output the PDF ---
try:
    pdf.output(OUTPUT_FILENAME, "F")
    print(f"PDF '{OUTPUT_FILENAME}' generated successfully.")
except Exception as e:
    print(f"Error generating PDF: {e}")